"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import { Image as KImage, Layer, Rect, Stage, Text, Transformer } from "react-konva";
import type Konva from "konva";
import type { DesignData, DesignElement } from "@/lib/design-data";
import { saveDesignAction } from "@/app/editor/actions";

function ImageNode({ element, onSelect, onMove }: { element: DesignElement; onSelect: () => void; onMove: (x: number, y: number) => void }) {
  const [image, setImage] = useState<HTMLImageElement>();
  useEffect(() => { if (!element.src) return; const value = new window.Image(); value.onload = () => setImage(value); value.src = element.src; }, [element.src]);
  return <KImage image={image} x={element.x} y={element.y} width={element.width} height={element.height} rotation={element.rotation} draggable onClick={onSelect} onDragEnd={(event) => onMove(event.target.x(), event.target.y())} />;
}

export function CardEditorV2({ id, initialName, initialData, width, height }: { id: string; initialName: string; initialData: DesignData; width: number; height: number }) {
  const [name, setName] = useState(initialName), [data, setData] = useState(initialData), [past, setPast] = useState<DesignData[]>([]), [selected, setSelected] = useState<string>(), [status, setStatus] = useState("Saved"), [preview, setPreview] = useState(false), [saving, startSaving] = useTransition();
  const node = useRef<Konva.Node | null>(null); const selectedElement = data.elements.find((item) => item.id === selected); const scale = Math.min(1, 720 / width, 720 / height);
  const change = (next: DesignData) => { setPast((items) => [...items.slice(-19), data]); setData(next); setStatus("Unsaved changes"); };
  const patch = (elementId: string, value: Partial<DesignElement>) => change({ ...data, elements: data.elements.map((item) => item.id === elementId ? { ...item, ...value } : item) });
  const upload = async (file: File) => { const body = new FormData(); body.set("file", file); const response = await fetch("/api/designs/upload", { method: "POST", body }); const result = await response.json() as { url?: string; error?: string }; if (!response.ok || !result.url) { setStatus(result.error || "Upload failed"); return; } const item: DesignElement = { id: `image-${Date.now()}`, type: "image", x: 120, y: 120, width: 420, height: 300, rotation: 0, src: result.url }; change({ ...data, elements: [...data.elements, item] }); setSelected(item.id); };
  const save = () => startSaving(async () => { setStatus("Saving…"); const result = await saveDesignAction(id, { name, designData: data }); setStatus(result.ok ? "Saved" : "Save failed"); });
  return <div className="min-h-screen bg-[#f5f1e8] text-forest"><header className="flex items-center justify-between border-b bg-white px-4 py-3"><a href="/dashboard/designs">← Back</a><input aria-label="Design name" value={name} onChange={(e) => { setName(e.target.value); setStatus("Unsaved changes"); }} className="w-48 text-center" /><div className="flex gap-2"><button disabled={!past.length} onClick={() => { const previous = past.at(-1); if (previous) { setPast((items) => items.slice(0, -1)); setData(previous); } }} className="rounded-full border px-3 py-2 text-xs">Undo</button><button onClick={() => setPreview(!preview)} className="rounded-full border px-3 py-2 text-xs">{preview ? "Edit" : "Preview"}</button><button onClick={save} disabled={saving} className="rounded-full bg-forest px-4 py-2 text-xs text-white">{saving ? "Saving…" : "Save"}</button></div></header><main className="mx-auto grid max-w-6xl gap-4 p-4 lg:grid-cols-[180px_1fr_240px]"><aside className="space-y-2"><button onClick={() => change({ ...data, elements: [...data.elements, { id: `text-${Date.now()}`, type: "text", x: width / 2 - 200, y: height / 2, width: 400, height: 80, rotation: 0, text: "Your text", style: { fontSize: 64, color: "#203b32", align: "center" } }] })} className="w-full rounded-xl bg-white p-3 text-sm">＋ Text</button><label className="block w-full cursor-pointer rounded-xl bg-white p-3 text-center text-sm">＋ Photo<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file); }} /></label></aside><section className="flex min-h-[65vh] items-center justify-center overflow-hidden rounded-2xl bg-[#ded8ca] p-3"><Stage width={width * scale} height={height * scale} scaleX={scale} scaleY={scale}><Layer>{data.elements.map((item) => item.type === "text" ? <Text key={item.id} {...item} text={item.text} fontSize={item.style?.fontSize} fill={item.style?.color} align={item.style?.align} draggable={!preview} onClick={() => setSelected(item.id)} onDragEnd={(event) => patch(item.id, { x: event.target.x(), y: event.target.y() })} /> : item.type === "image" ? <ImageNode key={item.id} element={item} onSelect={() => setSelected(item.id)} onMove={(x, y) => patch(item.id, { x, y })} /> : <Rect key={item.id} {...item} fill={item.fill || "#c59d5f"} draggable={!preview} onClick={() => setSelected(item.id)} />)}{selected && !preview && <Transformer ref={(transformer) => { if (transformer && node.current) transformer.nodes([node.current]); }} />}</Layer></Stage></section><aside className="rounded-2xl bg-white p-4"><p className="text-xs uppercase text-forest/60">{status}</p>{selectedElement?.type === "text" && <label className="mt-4 block text-xs">Text<input aria-label="Text content" value={selectedElement.text || ""} onChange={(e) => patch(selectedElement.id, { text: e.target.value })} /></label>}</aside></main></div>;
}
